# acpctl bash completion script
# Generated by acpctl completion bash
# Source this file to enable completions: source /path/to/acpctl.bash

_acpctl_complete() {
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    mapfile -t COMPREPLY < <(acpctl __complete "${COMP_WORDS[@]:1}")
}

complete -o default -F _acpctl_complete acpctl
