# acpctl fish completion script
# Generated by acpctl completion fish
# Copy this file to ~/.config/fish/completions/acpctl.fish

function __acpctl_complete
    acpctl __complete (commandline -opc | string split ' ')[2..-1]
end

complete -c acpctl -f -a "(__acpctl_complete)"
