#compdef acpctl
# acpctl zsh completion script
# Generated by acpctl completion zsh
# Place this file in a directory in your $fpath or source it directly

_acpctl() {
    local -a comps
    comps=("${(@f)$(acpctl __complete "${words[@]:1}")}")
    _describe 'acpctl values' comps
}

compdef _acpctl acpctl
