function __acpctl_complete
    # Fish completion function for acpctl
end

complete -c acpctl -f

complete -c acpctl -n '__fish_use_subcommand' -a 'ci' -d 'CI and local gate helpers'
complete -c acpctl -n '__fish_use_subcommand' -a 'env' -d 'Strict .env access helpers'
complete -c acpctl -n '__fish_use_subcommand' -a 'chargeback' -d 'Typed chargeback rendering helpers'
complete -c acpctl -n '__fish_use_subcommand' -a 'ops' -d 'Operator reporting workflows'
complete -c acpctl -n '__fish_use_subcommand' -a 'status' -d 'Aggregated system health overview'
complete -c acpctl -n '__fish_use_subcommand' -a 'health' -d 'Run service health checks'
complete -c acpctl -n '__fish_use_subcommand' -a 'doctor' -d 'Environment preflight diagnostics'
complete -c acpctl -n '__fish_use_subcommand' -a 'benchmark' -d 'Lightweight local performance baseline'
complete -c acpctl -n '__fish_use_subcommand' -a 'smoke' -d 'Run truthful runtime smoke checks'
complete -c acpctl -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completion scripts'
complete -c acpctl -n '__fish_use_subcommand' -a 'onboard' -d 'Launch the guided onboarding wizard'
complete -c acpctl -n '__fish_use_subcommand' -a 'deploy' -d 'Typed evidence and artifact workflows'
complete -c acpctl -n '__fish_use_subcommand' -a 'validate' -d 'Configuration and policy validation operations'
complete -c acpctl -n '__fish_use_subcommand' -a 'db' -d 'Database backup, restore, and inspection operations'
complete -c acpctl -n '__fish_use_subcommand' -a 'key' -d 'Virtual key lifecycle operations'
complete -c acpctl -n '__fish_use_subcommand' -a 'cert' -d 'TLS certificate lifecycle operations'
complete -c acpctl -n '__fish_use_subcommand' -a 'upgrade' -d 'Plan, validate, execute, and roll back host-first upgrades'
complete -c acpctl -n '__fish_use_subcommand' -a 'host' -d 'Host-first deployment and operations'
complete -c acpctl -n '__fish_use_subcommand' -a 'help' -d 'Show this help message'

complete -c acpctl -n '__fish_seen_subcommand_from ci' -a 'should-run-runtime' -d 'Decide whether runtime checks should run'
complete -c acpctl -n '__fish_seen_subcommand_from ci' -a 'wait' -d 'Wait for services to become healthy'
complete -c acpctl -n '__fish_seen_subcommand_from env' -a 'get' -d 'Read a single env key without shell execution'
complete -c acpctl -n '__fish_seen_subcommand_from chargeback' -a 'report' -d 'Generate canonical chargeback report artifacts'
complete -c acpctl -n '__fish_seen_subcommand_from chargeback' -a 'render' -d 'Render canonical chargeback JSON or CSV'
complete -c acpctl -n '__fish_seen_subcommand_from chargeback' -a 'payload' -d 'Render canonical chargeback webhook payload JSON'
complete -c acpctl -n '__fish_seen_subcommand_from ops' -a 'report' -d 'Render a canonical operator status report'
complete -c acpctl -n '__fish_seen_subcommand_from benchmark' -a 'baseline' -d 'Run the local gateway performance baseline'
complete -c acpctl -n '__fish_seen_subcommand_from completion' -a 'bash' -d 'Generate Bash completion script'
complete -c acpctl -n '__fish_seen_subcommand_from completion' -a 'zsh' -d 'Generate Zsh completion script'
complete -c acpctl -n '__fish_seen_subcommand_from completion' -a 'fish' -d 'Generate Fish completion script'
complete -c acpctl -n '__fish_seen_subcommand_from deploy' -a 'release-bundle' -d 'Build deployment release bundle'
complete -c acpctl -n '__fish_seen_subcommand_from deploy' -a 'readiness-evidence' -d 'Generate and verify dated readiness evidence'
complete -c acpctl -n '__fish_seen_subcommand_from deploy' -a 'pilot-closeout-bundle' -d 'Assemble and verify a pilot closeout evidence bundle'
complete -c acpctl -n '__fish_seen_subcommand_from deploy' -a 'artifact-retention' -d 'Enforce document artifact retention policy'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'lint' -d 'Run static validation/lint gate'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'config' -d 'Validate deployment configuration (use --production for host contract checks)'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'detections' -d 'Validate detection rule output'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'siem-queries' -d 'Validate SIEM query sync'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'public-hygiene' -d 'Fail when local-only files are tracked by git'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'license' -d 'Validate license policy structure and restricted references'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'supply-chain' -d 'Run supply-chain policy and digest validation'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'secrets-audit' -d 'Run deterministic tracked-file secrets audit'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'compose-healthchecks' -d 'Validate Docker Compose healthchecks'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'headers' -d 'Validate Go source file header policy'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'env-access' -d 'Fail on direct environment access outside internal/config'
complete -c acpctl -n '__fish_seen_subcommand_from validate' -a 'security' -d 'Run Make-composed security gate (hygiene, secrets, license, supply chain)'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'status' -d 'Show database status and statistics'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'backup' -d 'Create database backup'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'backup-retention' -d 'Enforce backup retention policy'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'restore' -d 'Restore embedded database from backup'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'off-host-drill' -d 'Validate a staged off-host backup copy and emit replacement-host recovery evidence'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'shell' -d 'Open database shell'
complete -c acpctl -n '__fish_seen_subcommand_from db' -a 'dr-drill' -d 'Create a fresh backup and verify restore into a scratch database'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'gen' -d 'Generate a standard virtual key'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'list' -d 'List virtual keys'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'inspect' -d 'Inspect a virtual key and its usage'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'rotate' -d 'Stage rotation for a virtual key'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'revoke' -d 'Revoke a virtual key by alias'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'gen-dev' -d 'Generate a developer key'
complete -c acpctl -n '__fish_seen_subcommand_from key' -a 'gen-lead' -d 'Generate a team-lead key'
complete -c acpctl -n '__fish_seen_subcommand_from cert' -a 'list' -d 'List tracked TLS certificates'
complete -c acpctl -n '__fish_seen_subcommand_from cert' -a 'inspect' -d 'Inspect one certificate'
complete -c acpctl -n '__fish_seen_subcommand_from cert' -a 'check' -d 'Validate certificate expiry and live TLS state'
complete -c acpctl -n '__fish_seen_subcommand_from cert' -a 'renew' -d 'Trigger controlled certificate reissuance'
complete -c acpctl -n '__fish_seen_subcommand_from cert' -a 'renew-auto' -d 'Install the automatic certificate renewal timer'
complete -c acpctl -n '__fish_seen_subcommand_from upgrade' -a 'plan' -d 'Show the explicit supported upgrade plan'
complete -c acpctl -n '__fish_seen_subcommand_from upgrade' -a 'check' -d 'Validate the upgrade path, config migrations, and host convergence'
complete -c acpctl -n '__fish_seen_subcommand_from upgrade' -a 'execute' -d 'Execute the supported host-first upgrade workflow'
complete -c acpctl -n '__fish_seen_subcommand_from upgrade' -a 'rollback' -d 'Restore the pre-upgrade snapshots from a recorded upgrade run'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'preflight' -d 'Validate host readiness'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'check' -d 'Run declarative host preflight/check mode'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'apply' -d 'Run declarative host apply/converge'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'install' -d 'Install systemd service and automated backup timer'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'uninstall' -d 'Uninstall systemd service and automated backup timer'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'service-status' -d 'Show service and backup timer status'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'service-start' -d 'Start the systemd service'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'service-stop' -d 'Stop the systemd service'
complete -c acpctl -n '__fish_seen_subcommand_from host' -a 'service-restart' -d 'Restart the systemd service'
